// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/models/wiki_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 1569987207353720729),
      name: 'WikiModel',
      lastPropertyId: const obx_int.IdUid(8, 4197122974869718201),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4452892298107845010),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7804665952564436687),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 9162412333185441843),
            name: 'summary',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 392103104519535709),
            name: 'introduction',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1498651991067414389),
            name: 'lastModified',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1193293057735572847),
            name: 'createdOn',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 9012300311397530993),
            name: 'sectionsTitles',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4197122974869718201),
            name: 'sectionsContents',
            type: 30,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 1569987207353720729),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    WikiModel: obx_int.EntityDefinition<WikiModel>(
        model: _entities[0],
        toOneRelations: (WikiModel object) => [],
        toManyRelations: (WikiModel object) => {},
        getId: (WikiModel object) => object.id,
        setId: (WikiModel object, int id) {
          object.id = id;
        },
        objectToFB: (WikiModel object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final summaryOffset = fbb.writeString(object.summary);
          final introductionOffset = fbb.writeString(object.introduction);
          final sectionsTitlesOffset = fbb.writeList(object.sectionsTitles
              .map(fbb.writeString)
              .toList(growable: false));
          final sectionsContentsOffset = fbb.writeList(object.sectionsContents
              .map(fbb.writeString)
              .toList(growable: false));
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, summaryOffset);
          fbb.addOffset(3, introductionOffset);
          fbb.addInt64(4, object.lastModified.millisecondsSinceEpoch);
          fbb.addInt64(5, object.createdOn.millisecondsSinceEpoch);
          fbb.addOffset(6, sectionsTitlesOffset);
          fbb.addOffset(7, sectionsContentsOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final summaryParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final introductionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final sectionsTitlesParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGet(buffer, rootOffset, 16, []);
          final sectionsContentsParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGet(buffer, rootOffset, 18, []);
          final createdOnParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));
          final lastModifiedParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));
          final object = WikiModel(
              idParam,
              titleParam,
              summaryParam,
              introductionParam,
              sectionsTitlesParam,
              sectionsContentsParam,
              createdOnParam,
              lastModifiedParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [WikiModel] entity fields to define ObjectBox queries.
class WikiModel_ {
  /// See [WikiModel.id].
  static final id =
      obx.QueryIntegerProperty<WikiModel>(_entities[0].properties[0]);

  /// See [WikiModel.title].
  static final title =
      obx.QueryStringProperty<WikiModel>(_entities[0].properties[1]);

  /// See [WikiModel.summary].
  static final summary =
      obx.QueryStringProperty<WikiModel>(_entities[0].properties[2]);

  /// See [WikiModel.introduction].
  static final introduction =
      obx.QueryStringProperty<WikiModel>(_entities[0].properties[3]);

  /// See [WikiModel.lastModified].
  static final lastModified =
      obx.QueryDateProperty<WikiModel>(_entities[0].properties[4]);

  /// See [WikiModel.createdOn].
  static final createdOn =
      obx.QueryDateProperty<WikiModel>(_entities[0].properties[5]);

  /// See [WikiModel.sectionsTitles].
  static final sectionsTitles =
      obx.QueryStringVectorProperty<WikiModel>(_entities[0].properties[6]);

  /// See [WikiModel.sectionsContents].
  static final sectionsContents =
      obx.QueryStringVectorProperty<WikiModel>(_entities[0].properties[7]);
}
